spring:
  application:
    name: spring-cloud-eureka
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
---
spring:
  profiles: eureka-01
eureka:
  instance:
    hostname: eureka-01
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/

---
spring:
  profiles: eureka-02
server:
  port: 8762
eureka:
  instance:
    hostname: eureka-02
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/

---
spring:
  profiles: eureka-03
server:
  port: 8763
eureka:
  instance:
    hostname: eureka-03
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/